# railway.toml

[build]
  command = "npm install --prefix frontend && npm run build --prefix frontend && pip install -r backend/requirements.txt"
  output = "backend" # O diretório onde o seu app Flask está
