name: Lint and Build

on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      # Passo 1: Fazer checkout do código
      - name: Check out the code
        uses: actions/checkout@v2

      # Passo 2: Configurar o Miniconda
      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: 3.9
          auto-activate-base: false
          activate-environment: myenv  # Nome do ambiente a ser criado

      # Passo 3: Atualizar o ambiente Conda
      - name: Update Conda environment
        run: conda env update --file environment.yml --name myenv

      # Passo 4: Executar flake8
      - name: Run flake8
        run: |
          conda run --name myenv flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
