name: Build and Update Conda Environment

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Passo 1: Fazer checkout do código
    - name: Check out the code
      uses: actions/checkout@v2

    # Passo 2: Instalar Conda e configurar o ambiente
    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: 3.9  # Definir a versão do Python
        auto-activate-base: false
        activate-environment: myenv  # Nome do ambiente Conda a ser criado

    # Passo 3: Atualizar o ambiente Conda com o arquivo environment.yml
    - name: Update Conda environment
      run: conda env update --file environment.yml --name myenv

    # Passo 4: Instalar Telethon usando pip
    - name: Install Telethon with pip
      run: |
        conda activate myenv
        pip install telethon

    # Passo 5: Executar um script Python para verificar a instalação do Telethon
    - name: Run Python script
      run: |
        conda activate myenv
        python -c "import telethon; print(telethon.__version__)"
