name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Etapa para fazer checkout do código no repositório
      - name: Check out code
        uses: actions/checkout@v2
      
      # Etapa para configurar o Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      # Etapa para construir a imagem Docker
      - name: Build the Docker image
        run: |
          docker build . -t ${{ secrets.DOCKER_HUB_USERNAME }}/my_flask_app:latest
          
      # Etapa para logar no Docker Hub
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin
      
      # Etapa para enviar a imagem Docker para o Docker Hub
      - name: Push the Docker image
        run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/my_flask_app:latest
